Update build.yaml

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -14,8 +14,8 @@ jobs:
       - name: Create file named "test"
         run: echo "This is a test file" > hello.txt
 
-      - name: Force fail the job
-        run: exit 1
+      #- name: Force fail the job
+      #  run: exit 1
 
       - name: Upload artifact
         uses: actions/upload-artifact@v4
